# Generated by Django 4.1.1 on 2022-09-25 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'car_category',
                'verbose_name_plural': 'car_category',
                'db_table': 'car_category',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255)),
                ('about', models.TextField()),
                ('media', models.URLField()),
                ('description', models.TextField()),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='cars.carcategory')),
            ],
            options={
                'verbose_name': 'cars',
                'verbose_name_plural': 'cars',
                'db_table': 'cars',
            },
        ),
    ]
