# Generated by Django 4.1.1 on 2022-09-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcategory',
            name='type',
            field=models.CharField(choices=[('HATCHBACK', 'Hatchback'), ('SEDAN', 'Sedan'), ('SUV', 'Suv')], default='SEDAN', max_length=255),
        ),
    ]
